# Generated by Django 3.2.8 on 2021-10-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_firstname', models.CharField(default='', max_length=50)),
                ('person_lastname', models.CharField(default='', max_length=30)),
                ('person_email', models.EmailField(default='', max_length=30)),
                ('person_password', models.CharField(default='', max_length=30)),
                ('person_gender', models.CharField(default='', max_length=300)),
                ('person_dob', models.DateField()),
            ],
        ),
    ]
